import model.NpcStats
import net.runelite.api.NpcID._

object ManualRename {

  def apply(npc: NpcStats) = npc.name = Some(renames.getOrElse(npc.id.get, npc.name.get))

  val renames: Map[Int, String] = Map(
    ZULRAH -> "Zulrah (Serpentine/Ranged)",
    ZULRAH_2043 -> "Zulrah (Magma/Melee)",
    ZULRAH_2044 -> "Zulrah (Tanzanite/Mage)",
    NYLOCAS_MATOMENOS -> "Nylocas Matomenos (Maiden)",
    NYLOCAS_ISCHYROS_8345 -> "Nylocas Ischyros (Big)",
    NYLOCAS_TOXOBOLOS_8346 -> "Nylocas Toxobolos (Big)",
    NYLOCAS_HAGIOS_8347 -> "Nylocas Hagios (Big)",
    NYLOCAS_ISCHYROS_8351 -> "Nylocas Ischyros (Big)",
    NYLOCAS_TOXOBOLOS_8352 -> "Nylocas Toxobolos (Big)",
    NYLOCAS_HAGIOS_8353 -> "Nylocas Hagios (Big)",
    VERZIK_VITUR_8369 -> "Verzik Vitur (P1/Throne)",
    VERZIK_VITUR_8370 -> "Verzik Vitur (P1/Throne)",
    VERZIK_VITUR_8371 -> "Verzik Vitur (P1/Throne)",
    VERZIK_VITUR_8372 -> "Verzik Vitur (P2/Vampyre)",
    VERZIK_VITUR_8373 -> "Verzik Vitur (P2/Vampyre)",
    VERZIK_VITUR_8374 -> "Verzik Vitur (P3/Spider)",
    VERZIK_VITUR_8375 -> "Verzik Vitur (P3/Spider)",
    NYLOCAS_ISCHYROS_10858 -> "Nylocas Ischyros (Verzik)",
    NYLOCAS_TOXOBOLOS_10859 -> "Nylocas Toxobolos (Verzik)",
    NYLOCAS_HAGIOS_10860 -> "Nylocas Hagios (Verzik)",
    NYLOCAS_MATOMENOS_10862 -> "Nylocas Matomenos (Verzik)",
    THE_MAIDEN_OF_SUGADINTI_10814 -> "The Maiden of Sugadinti EM",
    NYLOCAS_MATOMENOS_10820 -> "Nylocas Matomenos EM (Maiden)",
    BLOOD_SPAWN_10821 -> "Blood Spawn EM",
    PESTILENT_BLOAT_10812 -> "Pestilent Bloat EM",
    NYLOCAS_ISCHYROS_10774 -> "Nylocas Ischyros EM",
    NYLOCAS_TOXOBOLOS_10775 -> "Nylocas Toxobolos EM",
    NYLOCAS_HAGIOS_10776 -> "Nylocas Hagios EM",
    NYLOCAS_ISCHYROS_10777 -> "Nylocas Ischyros EM (Big)",
    NYLOCAS_TOXOBOLOS_10778 -> "Nylocas Toxobolos EM (Big)",
    NYLOCAS_HAGIOS_10779 -> "Nylocas Hagios EM (Big)",
    NYLOCAS_ISCHYROS_10780 -> "Nylocas Ischyros EM",
    NYLOCAS_TOXOBOLOS_10781 -> "Nylocas Toxobolos EM",
    NYLOCAS_HAGIOS_10782 -> "Nylocas Hagios EM",
    NYLOCAS_ISCHYROS_10783 -> "Nylocas Ischyros EM (Big)",
    NYLOCAS_TOXOBOLOS_10784 -> "Nylocas Toxobolos EM (Big)",
    NYLOCAS_HAGIOS_10785 -> "Nylocas Hagios EM (Big)",
    NYLOCAS_VASILIAS_10787 -> "Nylocas Vasilias EM",
    NYLOCAS_VASILIAS_10788 -> "Nylocas Vasilias EM",
    NYLOCAS_VASILIAS_10789 -> "Nylocas Vasilias EM",
    SOTETSEG_10864 -> "Sotetseg EM",
    SOTETSEG_10865 -> "Sotetseg EM",
    XARPUS_10768 -> "Xarpus EM",
    XARPUS_10769 -> "Xarpus EM",
    VERZIK_VITUR_10830 -> "Verzik Vitur EM (P1/Throne)",
    VERZIK_VITUR_10831 -> "Verzik Vitur EM (P1/Throne)",
    VERZIK_VITUR_10832 -> "Verzik Vitur EM (P2/Vampyre)",
    VERZIK_VITUR_10833 -> "Verzik Vitur EM (P2/Vampyre)",
    VERZIK_VITUR_10834 -> "Verzik Vitur EM (P3/Spider)",
    VERZIK_VITUR_10835 -> "Verzik Vitur EM (P3/Spider)",
    WEB_10837 -> "Web EM",
    NYLOCAS_ISCHYROS_10841 -> "Nylocas Ischyros EM (Verzik)",
    NYLOCAS_TOXOBOLOS_10842 -> "Nylocas Toxobolos EM (Verzik)",
    NYLOCAS_HAGIOS_10843 -> "Nylocas Hagios EM (Verzik)",
    NYLOCAS_ATHANATOS_10844 -> "Nylocas Athanatos EM",
    NYLOCAS_MATOMENOS_10845 -> "Nylocas Matomenos EM (Verzik)",
    THE_MAIDEN_OF_SUGADINTI_10822 -> "The Maiden of Sugadinti HM",
    NYLOCAS_MATOMENOS_10828 -> "Nylocas Matomenos HM (Maiden)",
    BLOOD_SPAWN_10829 -> "Blood Spawn HM",
    PESTILENT_BLOAT_10813 -> "Pestilent Bloat HM",
    NYLOCAS_ISCHYROS_10791 -> "Nylocas Ischyros HM",
    NYLOCAS_TOXOBOLOS_10792 -> "Nylocas Toxobolos HM",
    NYLOCAS_HAGIOS_10793 -> "Nylocas Hagios HM",
    NYLOCAS_ISCHYROS_10794 -> "Nylocas Ischyros HM (Big)",
    NYLOCAS_TOXOBOLOS_10795 -> "Nylocas Toxobolos HM (Big)",
    NYLOCAS_HAGIOS_10796 -> "Nylocas Hagios HM (Big)",
    NYLOCAS_ISCHYROS_10797 -> "Nylocas Ischyros HM",
    NYLOCAS_TOXOBOLOS_10798 -> "Nylocas Toxobolos HM",
    NYLOCAS_HAGIOS_10799 -> "Nylocas Hagios HM",
    NYLOCAS_ISCHYROS_10800 -> "Nylocas Ischyros HM (Big)",
    NYLOCAS_TOXOBOLOS_10801 -> "Nylocas Toxobolos HM (Big)",
    NYLOCAS_HAGIOS_10802 -> "Nylocas Hagios HM (Big)",
    NYLOCAS_PRINKIPAS -> "Nylocas Prinkipas (Melee)",
    NYLOCAS_PRINKIPAS_10805 -> "Nylocas Prinkipas (Melee)",
    NYLOCAS_PRINKIPAS_10805 -> "Nylocas Prinkipas (Mage)",
    NYLOCAS_PRINKIPAS_10806 -> "Nylocas Prinkipas (Ranged)",
    NYLOCAS_VASILIAS_10808 -> "Nylocas Vasilias HM",
    NYLOCAS_VASILIAS_10809 -> "Nylocas Vasilias HM",
    NYLOCAS_VASILIAS_10810 -> "Nylocas Vasilias HM",
    SOTETSEG_10867 -> "Sotetseg HM",
    SOTETSEG_10868 -> "Sotetseg HM",
    XARPUS_10772 -> "Xarpus HM",
    XARPUS_10773 -> "Xarpus HM",
    VERZIK_VITUR_10847 -> "Verzik Vitur HM (P1/Throne)",
    VERZIK_VITUR_10848 -> "Verzik Vitur HM (P1/Throne)",
    VERZIK_VITUR_10849 -> "Verzik Vitur HM (P2/Vampyre)",
    VERZIK_VITUR_10850 -> "Verzik Vitur HM (P2/Vampyre)",
    VERZIK_VITUR_10851 -> "Verzik Vitur HM (P3/Spider)",
    VERZIK_VITUR_10852 -> "Verzik Vitur HM (P3/Spider)",
    WEB_10854 -> "Web HM",
    NYLOCAS_ISCHYROS_10858 -> "Nylocas Ischyros HM (Verzik)",
    NYLOCAS_TOXOBOLOS_10859 -> "Nylocas Toxobolos HM (Verzik)",
    NYLOCAS_HAGIOS_10860 -> "Nylocas Hagios HM (Verzik)",
    NYLOCAS_ATHANATOS_10861 -> "Nylocas Athanatos HM",
    NYLOCAS_MATOMENOS_10862 -> "Nylocas Matomenos HM (Verzik)",
  )

}
