

case class NpcStats(
                     var id: Option[Int],
                     var name: Option[String],
                     hitpoints: Option[Int],
                     att: Option[Int],
                     str: Option[Int],
                     `def`: Option[Int],
                     mage: Option[Int],
                     range: Option[Int],
                     attbns: Option[Int],
                     strbns: Option[Int],
                     amage: Option[Int],
                     mbns: Option[Int],
                     arange: Option[Int],
                     rngbns: Option[Int],
                     dstab: Option[Int],
                     dslash: Option[Int],
                     dcrush: Option[Int],
                     dmagic: Option[Int],
                     drange: Option[Int],
                     combat: Option[Int],
                     isDemon: Option[Boolean],
                     isDragon: Option[Boolean],
                     isKalphite: Option[Boolean],
                     isLeafy: Option[Boolean],
                     isUndead: Option[Boolean],
                     isVampyre: Option[Boolean],
                     isXerician: Option[Boolean],
                   ) {

  def toNewNpcStats(): NewNpcStats = {
    NewNpcStats(
      id = id.get,
      name = name.get,
      levelHp = hitpoints,
      levelAttack = att,
      levelStrength = str,
      levelDefense = `def`,
      levelMagic = mage,
      levelRanged = range,
      attackBonus = attbns,
      strengthBonus = strbns,
      magicAccuracy = amage,
      magicDamage = mbns,
      rangedAccuracy = arange,
      rangedStrength = rngbns,
      defenseStab = dstab,
      defenseSlash = dslash,
      defenseCrush = dcrush,
      defenseMagic = dmagic,
      defenseRanged = drange,
      combatLevel = combat,
      isDemon = isDemon,
      isDragon = isDragon,
      isKalphite = isKalphite,
      isLeafy = isLeafy,
      isUndead = isUndead,
      isVampyre = isVampyre,
      isXerician = isXerician,
    )
  }

}
